[package]
name = "ioreg"
version = "0.1.0"
authors = ["Zinc Developers <zinc@github.com>"]

[lib]
name = "ioreg"
plugin = true

[dev-dependencies.volatile_cell]
path = "../volatile_cell"

[dependencies]
syntaxext_lint = { git="https://github.com/Gyscos/syntaxext_lint", version="*" }
